scrape_configs:
#  - job_name: cadvisor
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#          - cadvisor:8080
  - job_name: collector
    honor_labels: true
    scrape_interval: 60s
    static_configs:
      - targets:
          - 127.0.0.1:9091

rule_files:
  - "/etc/prometheus/rules/*.yml"


alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 127.0.0.1:9093
