spring:
  profiles: docker

application:
  local:
    address: 0.0.0.0
    port: 8998
    secureport: 0
    runmode: dev
  groupId: docker

registry:
  skip: false
  address: api-registry
  port: 8761

gateway:
  address: gateway
  port: 9999

kafka:
  schemaRegistries:
  - host: kafka
    port: 8081
    protocol: http
  brokers:
  - host: kafka
    port: 9092

logs:
  appender:
    stdout:
      enabled: true
      level: TRACE
    default:
      enabled: true
      level: INFO
      maxfilesize: 25MB
      maxhistory: 1
      totalsizecap: 400MB
    detailed:
      enabled: true
      level: TRACE
      maxfilesize: 25MB
      maxhistory: 1
      totalsizecap: 400MB
    error:
      enabled: true
      level: ERROR
      maxfilesize: 25MB
      maxhistory: 1
      totalsizecap: 400MB

db:
  name: executordb
  host: postgres
  port: 5432
  sslmode: disable
  connectionTimeout: 10
  retryFactor: 2
  retryLimit: 90

ansible:
  delegatorUser: pcc
  sshPrivateKeyFile: /run/secrets/key
  sshUser: pcc
  dir: /home/ansible/infra
  inventory: /home/ansible/infra/inventory/sites/hosts.yml
  playbook: /home/ansible/infra/main.yml
  vault: /home/ansible/infra/vault/vault.yml
  callback: http://%s:8998/statuses/
  delegatorIp: 127.0.0.1
  allowConcurrency: false
  retry: 0

resources:
- name: id_rsa_ansible
  path: /run/secrets/key
- name: id_rsa_ansible_pub
  path: /etc/pccx/ssh.pub

tasks:
  poolSize: 6

monitoring:
  period: 60
  metrics:
  - prefix: memory
    file: /sys/fs/cgroup/memory/memory.stat
  - prefix: cpu
    file: /sys/fs/cgroup/cpu/cpuacct.stat
