#!/bin/sh

set -eo pipefail

. /usr/share/pccx/rc.sh

pccx wait service $HOST_POSTGRES $PORT_POSTGRES

pccx merge /home/scripts/microservice/yaml-combiner-alpine \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

pccx trace APIREGISTRY

/usr/libexec/pccx/eureka-client /run/config.yml &

sleep 3

java -jar \
	--add-opens "java.base/java.util=ALL-UNNAMED" \
	--add-opens "java.base/java.lang.reflect=ALL-UNNAMED" \
	--add-opens "java.base/java.text=ALL-UNNAMED" \
	--add-opens "java.desktop/java.awt.font=ALL-UNNAMED" \
	/home/registry-1.2-SNAPSHOT.jar
