#!/bin/sh

set -eo pipefail

. /usr/share/pccx/rc.sh

pccx wait service $HOST_POSTGRES $PORT_POSTGRES
pccx wait service $HOST_MONITOR $PORT_MONITOR
pccx wait service $HOST_PCCSERVER $PORT_PCCSERVER
pccx wait service $HOST_MAAS $PORT_MAAS
pccx wait service $HOST_KEYMANAGER $PORT_KEYMANAGER
pccx wait service $HOST_SECURITY $PORT_SECURITY
pccx wait service $HOST_USERMANAGEMENT $PORT_USERMANAGEMENT
pccx wait service $HOST_PLATINAMONITOR $PORT_PLATINAMONITOR

pccx merge /home/scripts/microservice/yaml-combiner-alpine \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

pccx trace GATEWAY

# FIXME integrate this...
/home/scripts/keystoreHandler.sh -t spring-gateway*.jar -p $gateway_keystore_password

pccx exec GATEWAY java \
	-D"spring.cloud.config.discovery.enabled=false" \
	-D"spring.cloud.gateway.httpclient.websocket.max-frame-payload-length=6553600" \
	-D"spring.cloud.config.override-system-properties=false" \
	-D"spring.profiles.active=docker" \
	-D"spring.cloud.config.failFast=false" \
	-D"spring.config.location=/run/config.yml" \
	-D"eureka.client.service-url.defaultZone=$URI_EUREKA" \
	-D"server.ssl.key-store-password=$gateway_keystore_password" \
	-D"spring.cloud.config.label=$CONFIG_BRANCH_GATEWAY" \
	-D"server.ssl.keyStoreType=pkcs12" \
	-jar spring-gateway*.jar
