#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

pccx wait postgres
pccx wait service $HOST_APIREGISTRY $PORT_APIREGISTRY
pccx wait service ${HOST_PCCSERVER} ${PORT_PCCSERVER}

pccx merge /home/scripts/microservice/yaml-combiner-alpine \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

pccx trace KEYMANAGER

# FIXME integrate this...
/home/scripts/microservice/initConfGenerator.sh -o conf/adminKey.yml \
	-a "$KEYMANAGER_ADMIN"
sleep 5

PGPASSWORD="$postgres_password" psql \
        -U "$POSTGRES_USER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_POSTGRES" \
        -f /home/scripts/db/init.sql \
        -v "role=$DB_USER_KEYMANAGER" \
        -v "passwd=$keymanager_db_password" \
        -v "db=$DB_NAME_KEYMANAGER" \
        -v "dbschema=$DB_SCHEMA_KEYMANAGER"
PGPASSWORD="$keymanager_db_password" psql \
        -U "$DB_USER_KEYMANAGER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_KEYMANAGER" \
        -f /home/scripts/db/schema.sql
PGPASSWORD="$postgres_password" psql \
        -U "$POSTGRES_USER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_KEYMANAGER" \
	-v "pccdb=$DB_NAME_PCC" \
	-v "pccdbHost=$HOST_POSTGRES" \
	-v "pccdbPort=$PORT_POSTGRES" \
	-v "pccdbUser=$DB_USER_PCC" \
	-v "pccdbPassword=$pcc_db_password" \
	-v "dbUser=$DB_USER_KEYMANAGER" \
	-v "adminUser=$POSTGRES_USER" \
        -f /home/scripts/db/post-init.sql

pccx exec KEYMANAGER java \
	-D"spring.profiles.active=docker" \
	-D"spring.datasource.url=jdbc:postgresql://$HOST_POSTGRES/$DB_NAME_KEYMANAGER" \
	-D"spring.datasource.username=$DB_USER_KEYMANAGER" \
	-D"spring.datasource.password=$keymanager_db_password" \
	-D"spring.cloud.config.failFast=false" \
	-D"eureka.client.service-url.defaultZone=$URI_EUREKA" \
	-D"spring.config.location=/run/config.yml" \
	-D"keystore.file=/var/lib/key-manager/keystore.jks" \
	-jar key-manager-*.jar
