#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

pccx wait postgres

pccx merge /home/scripts/microservice/yaml-combiner \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

pccx trace MAAS

# FIXME integrate this
/usr/bin/swagger.sh

PGPASSWORD="$postgres_password" psql \
        -U "$POSTGRES_USER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_POSTGRES" \
        -f /home/scripts/db/init.sql \
        -v "role=$DB_USER_MAAS" \
        -v "passwd=$maas_db_password" \
        -v "db=$DB_NAME_MAAS" \
        -v "dbschema=$DB_SCHEMA_MAAS"
PGPASSWORD="$maas_db_password" psql \
        -U "$DB_USER_MAAS" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_MAAS" \
        -f /home/scripts/db/schema.sql

pccx exec MAAS /home/maas \
	--overrideSystemProperties \
	--configProfile docker \
	--configUri "/run/config.yml" \
	--configBranch "$CONFIG_BRANCH_MAAS" \
	--dbHost "$HOST_POSTGRES" \
	--dbName "$DB_NAME_MAAS" \
	--dbUsername "$DB_USER_MAAS" \
	--dbPassword "$maas_db_password" \
	--phAccessKey "$PHONEHOME_ACCESS_KEY" \
	--phSecretKey "$phonehome_secret_key" \
	--useHostnameAsAddress \
	--useHostnameAsName \
	--registryAddress "$HOST_APIREGISTRY" \
	--maxRegistrationRetry 5 \
	--orchestrationGitPath=/home/orchestration
