#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

pccx merge /home/scripts/microservice/yaml-combiner \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

pccx trace MAILER

pccx exec MAILER /home/go-microservice-mailer \
	--configProfile docker \
	--configUri "/run/config.yml" \
	--configBranch "$CONFIG_BRANCH_MAILER" \
	--phAccessKey "$PHONEHOME_ACCESS_KEY" \
	--phSecretKey "$phonehome_secret_key" \
	--useHostnameAsAddress \
	--useHostnameAsName \
	--registryAddress "$HOST_APIREGISTRY" \
	--maxRegistrationRetry 5
