#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

export MINIO_ROOT_USER
export MINIO_ROOT_PASSWORD
export MINIO_VOLUMES
export MINIO_PORT
export MINIO_ITERATIONS
export MINIO_PERIOD_SECS

pccx trace MINIO

# If command starts with an option, prepend minio.
test "$1" = "minio" || set -- minio "$@"

# su-exec to requested user, if service cannot run exec will fail.
docker_switch_user() {
	if [ -n "${MINIO_USERNAME}" ] && [ -n "${MINIO_GROUPNAME}" ]; then
		if [ -n "${MINIO_UID}" ] && [ -n "${MINIO_GID}" ]; then
			groupadd -f -g "$MINIO_GID" "$MINIO_GROUPNAME" &&
			useradd -u "$MINIO_UID" -g "$MINIO_GROUPNAME" \
				"$MINIO_USERNAME"
		else
			groupadd -f "$MINIO_GROUPNAME" &&
			useradd -g "$MINIO_GROUPNAME" "$MINIO_USERNAME"
		fi
		exec >/var/log/minio.log 2>&1 setpriv \
			--reuid="${MINIO_USERNAME}" \
			--regid="${MINIO_GROUPNAME}" \
			--keep-groups \
			"$@"
	    else
		exec >/var/log/minio.log 2>&1 "$@"
	 fi
}

## Switch to user if applicable.
docker_switch_user "$@"
