#!/bin/sh

set -e

LOGDIR=/var/log

. /run/secrets/env
. /run/secrets/pccx
. /usr/libexec/pccx/rc

minio_export

trace_if "$MINIO_TRACE_ENABLED"

# If command starts with an option, prepend minio.
if [ "${1}" != "minio" ]; then
    if [ -n "${1}" ]; then
        set -- minio "$@"
    fi
fi

# su-exec to requested user, if service cannot run exec will fail.
docker_switch_user() {
    if [ -n "${MINIO_USERNAME}" ] && [ -n "${MINIO_GROUPNAME}" ]; then
        if [ -n "${MINIO_UID}" ] && [ -n "${MINIO_GID}" ]; then
            groupadd -f -g "$MINIO_GID" "$MINIO_GROUPNAME" && \
                useradd -u "$MINIO_UID" -g "$MINIO_GROUPNAME" "$MINIO_USERNAME"
        else
            groupadd -f "$MINIO_GROUPNAME" && \
                useradd -g "$MINIO_GROUPNAME" "$MINIO_USERNAME"
        fi
        exec >$LOGDIR/stderr.log 2>&1 >$LOGDIR/stdout.log setpriv \
            --reuid="${MINIO_USERNAME}" \
            --regid="${MINIO_GROUPNAME}" \
            --keep-groups "$@"
    else
        exec >$LOGDIR/stderr.log 2>&1 >$LOGDIR/stdout.log "$@"
    fi
}

## Switch to user if applicable.
docker_switch_user "$@"
