#!/bin/sh

set -e

. /run/secrets/env
. /run/secrets/pccx
. /usr/libexec/pccx/rc

wait_for_url_pat "http://$APIREGISTRY_HOST:$APIREGISTRY_PORT" .
wait_for_host_port $REDIS_HOST $REDIS_PORT
wait_for_url_pat "http://$KAFKA_ADV_HOST:8081" "{}"

trace_if "$MONITOR_TRACE_ENABLED"

service=${0##*/}
combine_yaml /home/scripts/microservice/yaml-combiner-alpine \
	/home/conf/default.yml \
	/usr/lib/pccx/${service}.yml \
	/var/lib/pccx/${service}.yml

debug_if "$MONITOR_DEBUG_ENABLED" java \
        -D"eureka.client.service-url.defaultZone=$APIREGISTRY_URI" \
        -D"server.port=$MONITOR_PORT" \
        -D"spring.application.name=monitor" \
        -D"spring.cloud.config.failFast=false" \
        -D"spring.cloud.config.label=$MONITOR_CONFIG_BRANCH" \
        -D"spring.config.active.on-profile=docker" \
        -D"spring.config.location=/var/lib/pccx/${service}.yml" \
	-D"parquet.path=/var/lib/pccx/parquet" \
        -Xmx4096m \
	-jar monitor-*.jar
