#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

pccx wait url $URI_APIREGISTRY .
pccx wait url $URI_KAFKA "{}"
pccx wait service $HOST_REDIS $PORT_REDIS

pccx trace MONITOR

pccx merge /home/scripts/microservice/yaml-combiner-alpine \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

pccx exec MONITOR java \
        -D"eureka.client.service-url.defaultZone=$URI_EUREKA" \
        -D"server.port=$PORT_MONITOR" \
        -D"spring.application.name=monitor" \
        -D"spring.cloud.config.failFast=false" \
        -D"spring.cloud.config.label=$CONFIG_BRANCH_MONITOR" \
        -D"spring.config.active.on-profile=docker" \
        -D"spring.config.location=/run/config.yml" \
	-D"parquet.path=/var/lib/monitor/parquet" \
        -Xmx4096m \
	-jar monitor-*.jar
