#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

pccx wait service $HOST_GATEWAY $PORT_GATEWAY

pccx trace PCCUI

/usr/local/apache2/scripts/microservice/app-launcher \
	--overrideSystemProperties \
	--configProfile docker \
	--nodePort 80 \
	--appName gui \
	--configUri /usr/local/apache2/conf/application.yml \
	--useHostnameAsAddress \
	--useHostnameAsName \
	--registryAddress $HOST_APIREGISTRY \
	--maxRegistrationRetry 5 \
	--publicAddress "$HOST_PCCUI_IP" \
	--configBranch "$CONFIG_BRANCH_PCCUI" \
	--command httpd-foreground
