#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

pccx wait postgres
pccx wait url $URI_APIREGISTRY .
pccx wait url $URI_MINIO "Access Denied"
pccx wait url $URI_KAFKA "{}"
pccx wait service $HOST_PLATINAEXECUTOR $PORT_PLATINAEXECUTOR
pccx wait service $HOST_MAAS $PORT_MAAS

export MINIO_ROOT_USER
export MINIO_ROOT_PASSWORD=$minio_password
export MINIO_VOLUMES
export MINIO_PORT
export MINIO_ITERATIONS
export MINIO_PERIOD_SECS

pccx trace PCC

pccx merge /home/scripts/microservice/yaml-combiner \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

rsync -rt /home/new_ansible/ /home/ansible/
rsync -rt /home/new_orchestration/ /home/orchestration/
rsync -rt /home/new_kubespray/ /home/kubespray/

test -z "$HOST_PCCUI_IP" -o "$HOST_PCCUI_IP" = "0.0.0.0" ||
        sed -i "s/localhost/${HOST_PCCUI_IP}/g" /home/swagger/swagger.json

PGPASSWORD="$postgres_password" psql \
        -U "$POSTGRES_USER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_POSTGRES" \
        -f /home/scripts/db/init.sql \
        -v "role=$DB_USER_PCC" \
        -v "passwd=$pcc_db_password" \
        -v "db=$DB_NAME_PCC" \
        -v "dbschema=$DB_SCHEMA_PCC"
PGPASSWORD="$pcc_db_password" psql \
        -U "$DB_USER_PCC" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_PCC" \
        -f /home/scripts/db/schema.sql
PGPASSWORD="$postgres_password" psql \
        -U "$POSTGRES_USER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_PCC" \
        -f /home/scripts/db/post-init.sql

pccx exec PCC /home/pccserver \
        --overrideSystemProperties \
        --configProfile docker \
        --dbHost "$HOST_POSTGRES" \
        --dbName "$DB_NAME_PCC" \
        --dbUsername "$DB_USER_PCC" \
        --dbPassword "$pcc_db_password" \
        --configUri /run/config.yml \
        --phAccessKey "$PHONEHOME_ACCESS_KEY" \
        --phSecretKey "$phonehome_secret_key" \
        --useHostnameAsAddress \
        --useHostnameAsName \
        --registryAddress registry \
        --maxRegistrationRetry 5 \
        --publicAddress "$PCC_HOST_IP" \
        --configBranch "$CONFIG_BRANCH_PCC"
