#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

pccx wait postgres
pccx wait url $URI_APIREGISTRY .
pccx wait url $URI_MINIO "Access Denied"

export MINIO_ROOT_USER
export MINIO_ROOT_PASSWORD=$minio_password
export MINIO_VOLUMES
export MINIO_PORT
export MINIO_ITERATIONS
export MINIO_PERIOD_SECS

pccx trace PHONEHOME

cp /usr/share/pccx/${0##*/}.yml /run/config.yml

# FIXME this modifies the container; instead, use /run/...
mkdir -p /home/conf
test -f /home/conf/storage.yml ||
	pccx file create 0600 /home/conf/storage.yml cat <<-EOF
	destinationHost: platinadownload.auctacognitio.com
	destinationPort: 9001
	destinationBucket: phone-home
	accessKey: $PHONEHOME_ACCESS_KEY
	secretKey: "$phonehome_secret_key"
	dareKey: ""
	EOF

PGPASSWORD="$postgres_password" psql \
        -U "$POSTGRES_USER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_POSTGRES" \
        -f /home/scripts/db/init.sql \
        -v "role=$DB_USER_PHONEHOME" \
        -v "passwd=$phonehome_db_password" \
        -v "db=$DB_NAME_PHONEHOME" \
        -v "dbschema=$DB_SCHEMA_PHONEHOME"
PGPASSWORD="$phonehome_db_password" psql \
        -U "$DB_USER_PHONEHOME" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_PHONEHOME" \
        -f /home/scripts/db/schema.sql

pccx exec PHONEHOME /home/phone-home \
	--overrideSystemProperties \
	--configProfile docker \
	--dbHost "$HOST_POSTGRES" \
	--dbName "$DB_NAME_PHONEHOME" \
	--dbUsername "$DB_USER_PHONEHOME" \
	--dbPassword "$phonehome_db_password" \
	--configUri "/run/config.yml" \
	--customer "$PHONEHOME_CUSTOMER" \
	--services "platina-monitor,key-manager,monitor,registry,maas,node-exporter,mailer,user-management,platina-executor,cadvisor,gateway,pccserver,security" \
	--useHostnameAsAddress \
	--useHostnameAsName \
	--registryAddress registry \
	--maxRegistrationRetry 5
