#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

pccx wait postgres
pccx wait url $URI_KAFKA "{}"
pccx wait url $URI_APIREGISTRY .

pccx merge /home/scripts/microservice/yaml-combiner \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

pccx trace PLATINAEXECUTOR

PGPASSWORD="$POSTGRES_PASSWORD" psql \
        -U "$POSTGRES_USER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_POSTGRES" \
        -f /home/scripts/db/init.sql \
        -v "role=$DB_USER_PLATINAEXECUTOR" \
        -v "passwd=$DB_PASSWORD_PLATINAEXECUTOR" \
        -v "db=$DB_NAME_PLATINAEXECUTOR" \
        -v "dbschema=$DB_SCHEMA_PLATINAEXECUTOR"
PGPASSWORD="$DB_PASSWORD_PLATINAEXECUTOR" psql \
        -U "$DB_USER_PLATINAEXECUTOR" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_PLATINAEXECUTOR" \
        -f /home/scripts/db/schema.sql

pccx exec PLATINAEXECUTOR /home/platina-executor \
	--overrideSystemProperties \
	--configProfile docker \
	--configUri "/run/config.yml" \
	--configBranch "$CONFIG_BRANCH_PLATINAEXECUTOR" \
	--dbHost "$HOST_POSTGRES" \
	--dbName "$DB_NAME_PLATINAEXECUTOR" \
	--dbUsername "$DB_USER_PLATINAEXECUTOR" \
	--dbPassword "$DB_PASSWORD_PLATINAEXECUTOR" \
	--phAccessKey "$PHONEHOME_ACCESS_KEY" \
	--phSecretKey "$PHONEHOME_SECRET_KEY" \
	--useHostnameAsAddress \
	--useHostnameAsName \
	--registryAddress "$HOST_APIREGISTRY" \
	--maxRegistrationRetry 5
