#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

pccx wait postgres
pccx wait url $URI_APIREGISTRY .
pccx wait url $URI_PROMETHUS status
pccx wait url $URI_PUSHGATEWAY status

pccx merge /home/scripts/microservice/yaml-combiner \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

pccx trace PLATINAMONITOR

PGPASSWORD="$postgres_password" psql \
        -U "$POSTGRES_USER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_POSTGRES" \
        -f /home/scripts/db/init.sql \
        -v "role=$DB_USER_PLATINAMONITOR" \
        -v "passwd=$platinamonitor_db_password" \
        -v "db=$DB_NAME_PLATINAMONITOR" \
        -v "dbschema=$DB_SCHEMA_PLATINAMONITOR"
PGPASSWORD="$platinamonitor_db_password" psql \
        -U "$DB_USER_PLATINAMONITOR" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_PLATINAMONITOR" \
        -f /home/scripts/db/schema.sql
PGPASSWORD="$postgres_password" psql \
        -U "$POSTGRES_USER" \
        -h "$HOST_POSTGRES" \
        -e "$DB_NAME_PLATINAMONITOR" \
        -f /home/scripts/db/post-init.sql

pccx exec PLATINAMONITOR /home/platina-monitor \
	--overrideSystemProperties \
	--configProfile docker \
	--configUri "/run/config.yml" \
	--configBranch "$CONFIG_BRANCH_PLATINAMONITOR" \
	--dbHost "$HOST_POSTGRES" \
	--dbName "$DB_NAME_PLATINAMONITOR" \
	--dbUsername "$DB_USER_PLATINAMONITOR" \
	--dbPassword "$platinamonitor_db_password" \
	--phAccessKey "$PHONEHOME_ACCESS_KEY" \
	--phSecretKey "$phonehome_secret_key" \
	--useHostnameAsAddress \
	--useHostnameAsName \
	--registryAddress "$HOST_APIREGISTRY" \
	--maxRegistrationRetry 5
