#!/bin/sh

set -e

. /usr/share/pccx/rc.sh

export MINIO_ROOT_USER
export MINIO_ROOT_PASSWORD=$minio_password
export MINIO_VOLUMES
export MINIO_PORT
export MINIO_ITERATIONS
export MINIO_PERIOD_SECS

pccx wait url $URI_APIREGISTRY .
pccx wait service $HOST_SECURITY $PORT_SECURITY
pccx wait url $URI_MINIO "Access Denied"

pccx trace USERMANAGEMENT

pccx merge /home/scripts/microservice/yaml-combiner-alpine \
	/home/conf/default.yml /usr/share/pccx/${0##*/}.yml /run/config.yml

pccx exec USERMANAGEMENT java \
	-D"eureka.client.service-url.defaultZone=$URI_EUREKA" \
	-D"server.port=$PORT_USERMANAGEMENT" \
	-D"spring.application.name=user-management" \
	-D"spring.cloud.config.failFast=false" \
	-D"spring.config.active.on-profile=docker" \
	-D"spring.config.location=/run/config.yml" \
	-D"spring.datasource.password=$usermanagement_db_password" \
	-D"spring.datasource.username=$DB_USER_USERMANAGEMENT" \
	-jar user-management-*.jar
