#!/bin/sh

set -e

. /run/secrets/env
. /run/secrets/pccx
. /usr/libexec/pccx/rc

minio_export

wait_for_url_pat "http://$APIREGISTRY_HOST:$APIREGISTRY_PORT" .
wait_for_host_port $SECURITY_HOST $SECURITY_PORT
wait_for_url_pat "http://$MINIO_HOST:$MINIO_PORT" "Access Denied"

trace_if "$USERMANAGEMENT_TRACE_ENABLED"

service=${0##*/}
combine_yaml /home/scripts/microservice/yaml-combiner-alpine \
	/home/conf/default.yml \
	/usr/lib/pccx/${service}.yml \
	/var/lib/pccx/${service}.yml

debug_if "$USERMANAGEMENT_DEBUG_ENABLED" java \
	-D"eureka.client.service-url.defaultZone=$APIREGISTRY_URI" \
	-D"server.port=$USERMANAGEMENT_PORT" \
	-D"spring.application.name=user-management" \
	-D"spring.cloud.config.failFast=false" \
	-D"spring.config.active.on-profile=docker" \
	-D"spring.config.location=/var/lib/pccx/${service}.yml" \
	-D"spring.datasource.password=$USERMANAGEMENT_DB_PASSWORD" \
	-D"spring.datasource.username=$USERMANAGEMENT_DB_USER" \
	-jar user-management-*.jar
