server:
  port: 8084
  max-http-header-size: 65536
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

keystore:
  pwd: aucta2018
  file: /home/keystore.jks
  alias: aucta
  type: PKCS12

key:
  size: 2048
  algorithm: RSA

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/key_manager
    driver-class-name: org.postgresql.Driver
  application:
    name: key-manager
  profiles: docker

security:
  tenant:
    filter:
      enable: true

logs:
  appender:
    stdout:
      enabled: true
      level: TRACE
    default:
      enabled: true
      level: INFO
      maxhistory: 3
      maxfilesize: 500MB
      totalsizecap: 1GB
    detailed:
      historypattern: yyyy-MM-dd
      enabled: true
      level: TRACE
      maxhistory: 5
      maxfilesize: 500MB
      totalsizecap: 2GB
    error:
      enabled: true
      maxfilesize: 500MB
      totalsizecap: 2GB

logging:
  level:
    org.hibernate: ERROR
    org.postgresql: ERROR
    org.apache.coyote: INFO

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'

phone-home:
  conf:
    path: /home/conf
  log:
    path: /home/logs
  storage:
    endpoint: http://localhost:9000
